name: Aria2 Downloader

on:
  gollum # Trigger when wiki pages are edited

jobs:
  download-from-wiki:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Install aria2
        run: |
          sudo apt update
          sudo apt install -y aria2

      - name: Clone Wiki Repository
        run: |
          git clone "https://github.com/${GITHUB_REPOSITORY}.wiki.git"

      - name: Find Updated Markdown File
        id: find_md
        run: |
          WIKI_DIR=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2).wiki
          cd "$WIKI_DIR"
          MD_FILE=$(git log --pretty=format: -1 --name-only *.md | grep '\.md$' | head -n1)
          echo "MD_FILE=$MD_FILE" >> $GITHUB_ENV
          cd ..
          echo "Found updated markdown file: $MD_FILE"

      - name: Create downloads directory
        run: mkdir -p ./downloads

      - name: Download Files with aria2 (no seeding)
        run: |
          WIKI_DIR=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2).wiki
          aria2c \
            --dir=./downloads \
            --input-file="$WIKI_DIR/${{ env.MD_FILE }}" \
            --allow-overwrite=true \
            --continue=true \
            --max-concurrent-downloads=3 \
            --seed-time=0

      - name: List downloaded files
        run: ls -la ./downloads

      - name: Upload artifact for download
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files
          path: ./downloads/
